/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;

import SM.PCS.Graficos.Herramienta;
import SM.PCS.IU.Lienzo2D;
import SMM.PCS.Eventos.LienzoAdapter;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.PointerInfo;
import java.awt.peer.MouseInfoPeer;


/**
 *
 * @author pabloc
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private Point puntero; //Coordenadas del ratón en la ventana interna
    
    /** Creates new form VentanaInterna */
    public VentanaInterna() {
        initComponents();
        
        LienzoAdapter manejador = new LienzoAdapter();
        this.getLienzo2D().addLienzoAdapter(manejador);
        
        this.puntero = new Point();
    }

    
    public void setHerramienta(Herramienta h) {
        this.lienzo2D.setHerramienta(h);
        System.out.println("Ventana interna: " + h);
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D = new SM.PCS.IU.Lienzo2D();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo2D.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2DMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lienzo2DMouseDragged(evt);
            }
        });
        lienzo2D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lienzo2DMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzo2DMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzo2DMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMousePressed
        this.lienzo2D.pressed(evt);
    }//GEN-LAST:event_lienzo2DMousePressed

    private void lienzo2DMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseDragged
        this.lienzo2D.dragged(evt);
    }//GEN-LAST:event_lienzo2DMouseDragged

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2DMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseReleased
        this.lienzo2D.released(evt);
    }//GEN-LAST:event_lienzo2DMouseReleased

    private void lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseMoved
        MouseInfo mouse;
        this.puntero = MouseInfo.getPointerInfo().getLocation();
        //this.puntero = evt.getLocationOnScreen();
    }//GEN-LAST:event_lienzo2DMouseMoved

    public Point getCoordenadasPuntero() {
        return this.puntero;
    }
    
    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    /*public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }*/
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private SM.PCS.IU.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables

}
