/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.Icon;
import sm.image.LookupTableProducer;

/**
 *
 * @author pabloc
 */
public class PanelContraste extends javax.swing.JPanel {

    /**
     * Creates new form PanelContraste
     */
    public PanelContraste(String idS) {
        initComponents();
        
        int id = Integer.parseInt(idS);
        switch(id){
            case 0:
                bContraste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contraste.png")));
               
                break;
            case 1:
                bContraste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/iluminar.png")));
                
                break;
            case 2:
                bContraste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/oscurecer.png")));
                
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bContraste = new javax.swing.JButton();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bContraste, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bContraste, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bContraste;
    // End of variables declaration//GEN-END:variables
}
